# Generated by Django 4.2.7 on 2024-03-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DubaiSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='media/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('image_link', models.CharField(max_length=500)),
                ('product_url', models.CharField(max_length=500)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inquiry.dubaisites')),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ForeignOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('price', models.IntegerField()),
                ('discounted', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(max_length=500)),
                ('admin_checked', models.BooleanField(default=False)),
                ('profit', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=models.Model, related_name='orders', to='inquiry.foreignproduct')),
                ('user', models.ForeignKey(on_delete=models.Model, related_name='foreign_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
