# Generated by Django 4.2.7 on 2024-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
