# Generated by Django 4.2.7 on 2024-02-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
