# Generated by Django 4.2.7 on 2024-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='tracking_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
