# Generated by Django 4.2.7 on 2024-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_foreignorder_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default="2019-02-02"),
            preserve_default=False,
        ),
    ]
