# Generated by Django 4.2.7 on 2024-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_foreignorder_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='media/logos/')),
            ],
        ),
    ]
