# Generated by Django 4.2.7 on 2024-04-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_foreignorder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubaisites',
            name='fa_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
