# Generated by Django 4.2.7 on 2024-03-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_othersites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherSites',
            new_name='DubaiSites',
        ),
    ]
