# Generated by Django 4.2.7 on 2024-03-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_color'),
        ('inquiry', '0004_rename_othersites_dubaisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inquiry.dubaisites')),
            ],
            bases=('products.product',),
        ),
    ]
