# Generated by Django 4.2.7 on 2024-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_dubaisites_fa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
