# Generated by Django 4.2.7 on 2024-03-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_foreignproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignproduct',
            old_name='site',
            new_name='website',
        ),
    ]
