# Generated by Django 4.2.7 on 2024-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_foreignorder_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='derham',
            field=models.IntegerField(default=17000),
        ),
    ]
