# Generated by Django 4.2.7 on 2024-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_rename_site_foreignproduct_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignproduct',
            name='image_link',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
