# Generated by Django 4.2.7 on 2024-07-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_foreignorder_derham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='derham',
            field=models.BigIntegerField(default=17000),
        ),
    ]
