# Generated by Django 4.2.7 on 2024-03-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_foreignproduct_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignproduct',
            name='product_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
