# Generated by Django 4.2.7 on 2024-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_alter_foreignorder_derham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='derham',
            field=models.CharField(default='17000'),
        ),
    ]
