# Generated by Django 4.2.7 on 2024-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0008_alter_foreignorder_derham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='derham',
            field=models.IntegerField(default=17000),
        ),
    ]
