# Generated by Django 4.2.7 on 2024-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0008_foreignproduct_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=models.Model, related_name='orders', to='inquiry.foreignproduct'),
            preserve_default=False,
        ),
    ]
