# Generated by Django 4.2.7 on 2024-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0009_foreignorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
