# Generated by Django 4.2.7 on 2024-03-27 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiry', '0010_alter_foreignorder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignorder',
            name='user',
            field=models.ForeignKey(on_delete=models.Model, related_name='foreign_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
