# Generated by Django 4.2.7 on 2024-03-02 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'آقا'), ('f', 'خانم'), ('u', 'ترجیح میدم نگویم.')], default='u', max_length=1),
        ),
    ]
