# Generated by Django 4.2.7 on 2024-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='text',
            new_name='straight_address',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
