# Generated by Django 4.2.7 on 2024-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_text_address_straight_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='abs_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
