# Generated by Django 4.2.7 on 2024-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_last_send_way_deliveryinfo_last_send_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='last_send_way',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_method',
            field=models.CharField(choices=[('c', 'درون شهری'), ('b', 'اتوبوس'), ('p', 'پست معمولی'), ('t', 'تیپاکس (پس کرایه)')], default='p', max_length=1),
        ),
    ]
