# Generated by Django 4.2.7 on 2024-03-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cover',
            new_name='cover',
        ),
    ]
