# Generated by Django 4.2.7 on 2024-03-07 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_description_remove_product_more_info_and_more'),
        ('blog', '0002_rename_cover_category_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(related_name='articles', to='products.product'),
        ),
    ]
