# Generated by Django 4.2.7 on 2024-03-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_text_article_content_article_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Cover',
            new_name='cover',
        ),
    ]
