# Generated by Django 4.2.7 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_cover_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
