# Generated by Django 4.2.3 on 2024-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
