# Generated by Django 4.2.7 on 2024-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_tempcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_sync',
            field=models.BooleanField(default=True),
        ),
    ]
