# Generated by Django 4.2.10 on 2024-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigTitle', models.CharField(max_length=200)),
                ('smallTitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/banners/%Y/%m/')),
                ('for_what', models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('f1', 'fisrt1'), ('f2', 'fisrt2'), ('b1', 'big1'), ('e1', 'end1'), ('t1', 'category1'), ('t2', 'category2'), ('t3', 'category3'), ('ct', 'category page'), ('ds', 'dashboard'), ('ne', 'news'), ('au', 'aboutUs'), ('ay', 'aboutUsBanner'), ('co', 'contact'), ('fq', 'FAQ'), ('ff', 'full width FAQ'), ('to', 'Track Order'), ('ru', 'Rules')], max_length=2)),
                ('main_link', models.CharField(max_length=200)),
                ('out_link', models.CharField(max_length=200)),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
                ('arg', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
