# Generated by Django 4.2.3 on 2024-02-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigTitle', models.CharField(max_length=200)),
                ('smallTitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/banners/%Y/%m/')),
                ('for_what', models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('f1', 'fisrt1'), ('f2', 'fisrt2'), ('b1', 'big1'), ('e1', 'end1'), ('t1', 'category1'), ('t2', 'category2'), ('t3', 'category3'), ('ct', 'category page'), ('ds', 'dashboard'), ('ne', 'news'), ('au', 'aboutUs'), ('ay', 'aboutUsBanner'), ('co', 'contact'), ('fq', 'FAQ'), ('ff', 'full width FAQ'), ('to', 'Track Order'), ('ru', 'Rules')], max_length=2)),
                ('main_link', models.CharField(max_length=200)),
                ('out_link', models.CharField(max_length=200)),
                ('button', models.CharField(blank=True, max_length=200, null=True)),
                ('arg', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='layout.faqgroup')),
            ],
        ),
    ]
