# Generated by Django 4.2.7 on 2024-03-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alt', models.CharField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(upload_to='media/banners/%Y/%m/')),
                ('for_what', models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('b1', 'big1'), ('gl', 'گیزمولاگ')], max_length=2)),
                ('abs_link', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='media/config/logo/')),
                ('black_logo', models.ImageField(upload_to='media/config/logo/')),
                ('phone', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
                ('insta', models.URLField()),
                ('whatsapp', models.URLField()),
                ('telegram', models.URLField()),
                ('aboutUs', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('color', models.CharField(default='82981a', max_length=6)),
                ('e_namad', models.TextField()),
                ('gif', models.FileField(upload_to='media/config/logo/')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='media/faqs/pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(default='None', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='layout.faqgroup')),
            ],
        ),
    ]
