# Generated by Django 4.2.7 on 2024-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='arg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='main_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='out_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='smallTitle',
        ),
        migrations.AddField(
            model_name='banner',
            name='abs_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='color_title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
