# Generated by Django 4.2.7 on 2024-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_remove_banner_arg_remove_banner_main_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
