# Generated by Django 4.2.7 on 2024-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='for_what',
            field=models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('b1', 'big1')], max_length=2),
        ),
    ]
