# Generated by Django 4.2.7 on 2024-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_alter_banner_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='for_what',
            field=models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('b1', 'big1'), ('gl', 'گیزمولاگ')], max_length=2),
        ),
    ]
