# Generated by Django 4.2.7 on 2024-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_rename_text_banner_alt_remove_banner_bigtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
