# Generated by Django 4.2.7 on 2024-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
