# Generated by Django 4.2.7 on 2024-03-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0009_banner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(default='None', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default='None')),
            ],
        ),
    ]
