# Generated by Django 4.2.7 on 2024-03-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_rename_survey_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='media/config/logo/')),
                ('black_logo', models.ImageField(upload_to='media/config/logo/')),
                ('phone', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=200)),
                ('insta', models.URLField()),
                ('whatsapp', models.URLField()),
                ('telegram', models.URLField()),
                ('aboutUs', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('color', models.CharField(default='82981a', max_length=6)),
                ('e_namad', models.TextField()),
                ('gif', models.FileField(upload_to='media/config/logo/')),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
