# Generated by Django 4.2.7 on 2024-02-20 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_comment_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, default=None, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='media/receipt/%Y/%m/')),
                ('receipt_bool', models.BooleanField(default=False)),
                ('ref_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('packing', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('deliveried', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
