# Generated by Django 4.2.7 on 2024-03-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_bool',
        ),
    ]
