# Generated by Django 4.2.7 on 2024-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_receipt_remove_order_receipt_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
