# Generated by Django 4.2.7 on 2024-03-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_color'),
        ('orders', '0004_order_name_reciver_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
            preserve_default=False,
        ),
    ]
