# Generated by Django 4.2.7 on 2024-03-22 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_name_reciver_remove_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factor',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
