# Generated by Django 4.2.7 on 2024-03-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_deliveryinfo_last_send_way_and_more'),
        ('orders', '0005_remove_order_name_reciver_remove_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipient',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='accounts.deliveryinfo'),
        ),
    ]
