# Generated by Django 4.2.7 on 2024-03-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_reciver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
