# Generated by Django 4.2.7 on 2024-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_landing',
            field=models.BooleanField(default=False),
        ),
    ]
