# Generated by Django 4.2.7 on 2024-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
