# Generated by Django 4.2.7 on 2024-03-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_is_main_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
