# Generated by Django 4.2.7 on 2024-03-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_main_attribute_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
