# Generated by Django 4.2.7 on 2024-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_description_remove_product_more_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
